name: Schedule Job

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest  # FIXED: 'runs-on' must be lowercase and indented properly

    steps:
      - name: Print Message  # FIXED: steps must be indented under 'run-script'
        run: echo "Schedule Workflow"
